@{
    # Ordered severities to consider (leave Information so it surfaces when requested)
    Severity        = @('Error', 'Warning', 'Information')

    # Point to canonical custom rules module in ./rules
    CustomRulePath  = @('.\rules\00-SkyLedger.Rules.psm1')

    # Enable all built-in rules: leaving IncludeRules empty instructs PSScriptAnalyzer to use its default set.
    # Keep ExcludeRules empty so nothing is skipped.
    IncludeRules    = @(
        'PSAlignAssignmentStatement'
        'PSAvoidUsingCmdletAliases'
        'PSAvoidAssignmentToAutomaticVariable'
        'PSAvoidDefaultValueSwitchParameter'
        'PSAvoidDefaultValueForMandatoryParameter'
        'PSAvoidUsingEmptyCatchBlock'
        'PSAvoidExclaimOperator'
        'PSAvoidGlobalAliases'
        'PSAvoidGlobalFunctions'
        'PSAvoidGlobalVars'
        'PSAvoidInvokingEmptyMembers'
        'PSAvoidLongLines'
        'PSAvoidMultipleTypeAttributes'
        'PSAvoidNullOrEmptyHelpMessageAttribute'
        'PSAvoidOverwritingBuiltInCmdlets'
        'PSAvoidUsingPositionalParameters'
        'PSReservedCmdletChar'
        'PSReservedParams'
        'PSAvoidSemicolonsAsLineTerminators'
        'PSAvoidShouldContinueWithoutForce'
        'PSAvoidTrailingWhitespace'
        'PSAvoidUsingUsernameAndPasswordParams'
        'PSAvoidUsingAllowUnencryptedAuthentication'
        'PSAvoidUsingBrokenHashAlgorithms'
        'PSAvoidUsingComputerNameHardcoded'
        'PSAvoidUsingConvertToSecureStringWithPlainText'
        'PSAvoidUsingDeprecatedManifestFields'
        'PSAvoidUsingDoubleQuotesForConstantString'
        'PSAvoidUsingInvokeExpression'
        'PSAvoidUsingPlainTextForPassword'
        'PSAvoidUsingWMICmdlet'
        'PSAvoidUsingWriteHost'
        'PSUseCompatibleCommands'
        'PSUseCompatibleSyntax'
        'PSUseCompatibleTypes'
        'PSMisleadingBacktick'
        'PSMissingModuleManifestField'
        'PSPlaceCloseBrace'
        'PSPlaceOpenBrace'
        'PSPossibleIncorrectComparisonWithNull'
        'PSPossibleIncorrectUsageOfAssignmentOperator'
        'PSPossibleIncorrectUsageOfRedirectionOperator'
        'PSProvideCommentHelp'
        'PSReviewUnusedParameter'
        'PSUseApprovedVerbs'
        'PSUseBOMForUnicodeEncodedFile'
        'PSUseCmdletCorrectly'
        'PSUseCompatibleCmdlets'
        'PSUseConsistentIndentation'
        'PSUseConsistentWhitespace'
        'PSUseCorrectCasing'
        'PSUseDeclaredVarsMoreThanAssignments'
        'PSUseLiteralInitializerForHashtable'
        'PSUseOutputTypeCorrectly'
        'PSUseProcessBlockForPipelineCommand'
        'PSUsePSCredentialType'
        'PSShouldProcess'
        'PSUseShouldProcessForStateChangingFunctions'
        'PSUseSingularNouns'
        'PSUseSupportsShouldProcess'
        'PSUseToExportFieldsInManifest'
        'PSUseUsingScopeModifierInNewRunspaces'
        'PSUseUTF8EncodingForHelpFile'
        # DSC rules
        'PSDSCDscExamplesPresent'
        'PSDSCDscTestsPresent'
        'PSDSCReturnCorrectTypesForDSCFunctions'
        'PSDSCUseIdenticalMandatoryParametersForDSC'
        'PSDSCUseIdenticalParametersForDSC'
        'PSDSCStandardDSCFunctionsInResource'
        'PSDSCUseVerboseMessageInDSCResource'
        # Custom rules
        'PSCustomRule_StrictModeVersion'
        'PSCustomRule_ErrorActionPreferenceStop'
    )
    ExcludeRules    = @()
}